#!/bin/bash

# PostgreSQL installation script

while [ ${#} -gt 0 ]
do
    case ${1} in
        # PostgreSQL version
        '-V' | '--version')
            PG_VERSION=${2};
            shift;;
        
        (--)
            shift;
            break;;

        (-*)
            echo -e "${0} [Error]:\n Unrecognized option ${1}" 1>&2;
            exit 1;;

        (*)
            break;;
    esac
    shift
done

echo ${PG_VERSION}

# Packages to install
PKG="build-essential bison flex gettext make bzip2 libreadline-dev
    libnss-wrapper libssl-dev libxml2-dev libldap2-dev libossp-uuid-dev lbzip2
    zlib1g-dev wget locales"

# Environment variables ======================================================
PG_SRC="postgresql-${PG_VERSION}"
PG_SRC_F="${PG_SRC}.tar.bz2"
PG_URL="https://ftp.postgresql.org/pub/source/v${PG_VERSION}/${PG_SRC_F}"
PG_HOME='/usr/local/pgsql'
PG_BIN="${PG_HOME}/bin"
PG_DOC="${PG_HOME}/doc"
PG_MAN="${PG_HOME}/man"
POSTGRES_USER_HOME='/var/local/pgsql'
PGPYTHONPATH="${POSTGRES_USER_HOME}/python"
POSTGRES_USER='postgres'
POSTGRES_GROUP='postgres'
PGPYTHONPATH="${POSTGRES_USER_HOME}/python"
PG_LOG="${POSTGRES_USER_HOME}/log"



# Configure options to make
CONFIGURE_OPTS="\
    --prefix ${PG_HOME} \
    --bindir ${PG_BIN} \
    --with-python \
    --with-libxml \
    --with-openssl \
    --with-ldap \
    --with-uuid=ossp \
    --includedir=/usr/local/include \
    --mandir=${PG_MAN} \
    --docdir=${PG_DOC}"

# Number of jobs according to the number of processor cores +1
NJOBS="`expr \`cat /proc/cpuinfo | egrep ^processor | wc -l\` + 1`"

# Make options
MAKEOPTS="-j${NJOBS}"

# 64 bits
CHOST='x86_64-unknown-linux-gnu'

# Optimization flags to make
CFLAGS='-O2 -pipe'
CXXFLAGS="${CFLAGS}"

# PATH environment variable
PATH="${PG_BIN}:${PATH}"

# ============================================================================

# Refresh repositories
apt update

# Install packages
apt install -y ${PKG}

# Download bziped source code to /tmp directory
wget -qO - ${PG_URL} | tar -xjC /tmp/

# Heredoc to create a customized psql file profile
cat << EOF > /etc/skel/.psqlrc
\x auto
\set COMP_KEYWORD_CASE upper
\set HISTCONTROL ignoreboth
EOF

# Add system group 
groupadd -r ${POSTGRES_GROUP}

# Add system user
useradd -m -r \
    --shell /bin/bash\
    --gid ${POSTGRES_GROUP}\
    --home-dir ${POSTGRES_USER_HOME}\
    --skel /etc/skel\
    --comment 'PostgreSQL system user'\
    ${POSTGRES_USER}
        
# Make directories
mkdir -p \
    ${PG_STATS_TEMP}\
    ${PGDATA}\
    ${PG_LOG}\
    ${PGPYTHONPATH}

# Change ownership
chown -R ${POSTGRES_USER}:${POSTGRES_GROUP} ${POSTGRES_USER_HOME}

# Go to source directory
cd /tmp/${PG_SRC}

# Configure process with environment variable for Python binary
PYTHON='/usr/local/bin/python' ./configure ${CONFIGURE_OPTS}

# Make
make world

# Make install
make install-world

# Delete itself
rm -f ${0}